### ISSUE TITLE
ansible::section-keywords-regex should include gather_facts and strategy

### ISSUE THREAD

**Issue by chillum** [k1LoW/emacs-ansible#16]
this is a valid site.yml that looks kinda borked with ansible-mode:

```yaml
- hosts: default
  gather_facts: no
  strategy: free
  roles: [ deploy ]
```

`gather_facts` and `strategy` cannot be used in roles, so they should be included to `ansible::section-keywords-regex`

P.S. same applies to `connection` keyword:
```yaml
- hosts: db
  connection: local
  gather_facts: no
  roles:
    - deploy-db
```
